<?php
/**
 * Created by PhpStorm.
 * User: bishnubhusal
 * Date: 11/5/18
 * Time: 1:04 PM
 */

namespace App\Modules\FlashSales\Requests;


use App\Http\Requests\BaseRequest;

class CreateFlashSaleRequest extends BaseRequest
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}